title: Ancient theme
logo: /assets/logo.svg
description: Ancient is a theme for GitHub Pages.

remote_theme: mkettn/ancient-theme


header_pages:
  - index.md
  - about.md
  - another-page.md

footer_pages:
  - another-page.md
